In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
dataset = pd.read_csv('data.csv', sep=';')
dataset

Game  ReleaseDate  \
0                                  Dota 2         2013   
1                                Fortnite         2017   
2                          Arena of Valor         2015   
3    PLAYERUNKNOWN'S BATTLEGROUNDS Mobile         2017   
4           PLAYERUNKNOWN’S BATTLEGROUNDS         2017   
..                                    ...          ...   
624                               Pac-man         1981   
625                   Apex Legends Mobile         2022   
626          Ark: Survival Of The Fittest         2017   
627                     Rules Of Survival         2017   
628                         Knockout City         2021   

                               Genre  LANEarnings  OnlineEarnings  \
0    Multiplayer Online Battle Arena  31187903215     28085206696   
1                      Battle Royale  14911647191      4584213347   
2    Multiplayer Online Battle Arena   7039242725      6637330149   
3                      Battle Royale   6294769628      4072285932   
4                      Battle Royale   5233920306      3887534473   
..                               ...          ...             ...   
624                      Puzzle Game            0               0   
625                    Battle Royale            0               0   
626                    Battle Royale            0               0   
627                    Battle Royale            0               0   
628             Third-Person Shooter            0               0   

     TotalPlayers  TotalTournaments  AllEarnings  TierCompetitive  
0            4563              1742  59273109911                1  
1            6104              1149  19495860538                1  
2            1842               145  13676572874                1  
3            3423               233  10367055560                1  
4            3517               554   9121454779                1  
..            ...               ...          ...              ...  
624             0                 0            0                0  
625             0                 0            0                0  
626             0                 0            0                0  
627             0                 0            0                0  
628             0                 0            0                0  

[629 rows x 9 columns]

Untuk menampilkan dataset

In [ ]:
df_baru = dataset.loc[:,['Game','AllEarnings','TierCompetitive']]
df_baru

Game  AllEarnings  TierCompetitive
0                                  Dota 2  59273109911                1
1                                Fortnite  19495860538                1
2                          Arena of Valor  13676572874                1
3    PLAYERUNKNOWN'S BATTLEGROUNDS Mobile  10367055560                1
4           PLAYERUNKNOWN’S BATTLEGROUNDS   9121454779                1
..                                    ...          ...              ...
624                               Pac-man            0                0
625                   Apex Legends Mobile            0                0
626          Ark: Survival Of The Fittest            0                0
627                     Rules Of Survival            0                0
628                         Knockout City            0                0

[629 rows x 3 columns]

Mengecek data apabila terdapat nun atau tidak

In [ ]:
df_baru.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 629 entries, 0 to 628
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   Game             629 non-null    object
 1   AllEarnings      629 non-null    int64 
 2   TierCompetitive  629 non-null    int64 
dtypes: int64(2), object(1)
memory usage: 14.9+ KB


In [ ]:
df_baru.isnull().sum()

Game               0
AllEarnings        0
TierCompetitive    0
dtype: int64

Untuk mengetahui data type 

In [ ]:
x = df_baru[['Game','AllEarnings']].values
y = df_baru['TierCompetitive'].values

In [ ]:
print(x)

[[        138 59273109911]
 [        193 19495860538]
 [         21 13676572874]
 ...
 [         22           0]
 [        458           0]
 [        285           0]]


In [ ]:
print(y)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 3 2 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 4 3 3 3 3 4 4 3 3 3 3 3 4 3 4 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 3 4
 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 5 4 4 5 5 4 4 5 5 4 4 4 5 5 5 4 4 4
 4 4 4 4 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 4 5 5 5 5 5 5 5 5 5 5 5 5 5 5
 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
 5 5 4 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
 5 5 5 5 5 5 5 5 5 5 5 5 

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df_baru['Game'] = le.fit_transform(dataset['Game'].values)
y = le.fit_transform(y)

In [ ]:
print(df_baru)

     Game  AllEarnings  TierCompetitive
0     138  59273109911                1
1     193  19495860538                1
2      21  13676572874                1
3     377  10367055560                1
4     378   9121454779                1
..    ...          ...              ...
624   379            0                0
625    15            0                0
626    22            0                0
627   458            0                0
628   285            0                0

[629 rows x 3 columns]


In [ ]:
print(x,y)

[[        138 59273109911]
 [        193 19495860538]
 [         21 13676572874]
 ...
 [         22           0]
 [        458           0]
 [        285           0]] [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 3 2 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 4 3 3 3 3 4 4 3 3 3 3 3 4 3 4 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 3 4
 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4
 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 5 4 4 5 5 4 4 5 5 4 4 4 5 5 5 4 4 4
 4 4 4 4 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 4 5 5 5 5 5 5 5 5 5 5 5 5 5 5
 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
 5 5 4 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
 5 5 5 

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

In [ ]:
print(x_train)

[[        39    2692656]
 [        65  487944507]
 [       375 5302050846]
 ...
 [       440     158000]
 [       579    9247014]
 [        49         70]]


In [ ]:
print(x_test)

[[        261     7035378]
 [        214      210848]
 [        332         740]
 [        459      416009]
 [        448       70000]
 [        187    34027383]
 [        313         260]
 [        131         200]
 [        396      542102]
 [         91         100]
 [        483         600]
 [         35    18343044]
 [        417     5041692]
 [        488        9960]
 [          2     6584956]
 [        567       67941]
 [        422         400]
 [        352      140586]
 [        379           0]
 [        626   358846006]
 [         78     1063000]
 [        218           0]
 [        385     4053632]
 [        408      432000]
 [         75    81793470]
 [        107     1263141]
 [         24       11745]
 [        372     4603542]
 [        415       70000]
 [        329       15070]
 [         88         750]
 [         67   290921088]
 [        513   452704190]
 [         61          16]
 [        419    41058418]
 [        301        3000]
 [        363     7264516]
 

In [ ]:
print(y_train)

[5 3 1 5 4 5 5 0 5 5 5 3 0 5 4 4 5 5 0 5 0 0 5 5 5 5 4 0 5 4 0 5 5 0 4 0 0
 5 4 5 5 0 3 5 5 5 5 4 5 0 1 5 3 5 4 5 4 5 0 5 5 5 5 5 5 5 5 2 5 5 5 5 5 5
 5 4 5 0 5 4 5 5 5 5 5 5 4 0 5 5 4 2 3 5 5 5 5 4 0 5 5 4 5 0 5 5 5 5 5 4 5
 3 5 2 3 0 4 1 5 5 5 5 0 5 5 5 5 4 5 5 1 0 5 4 4 3 3 4 5 5 5 3 3 5 5 5 5 5
 5 5 5 5 3 5 5 5 5 4 4 4 3 5 0 5 4 3 5 5 5 5 3 5 1 5 5 5 5 1 4 5 4 5 0 2 5
 5 5 0 5 5 0 4 3 0 0 5 0 0 4 0 5 5 0 5 5 5 4 5 5 4 4 5 3 4 5 0 5 5 5 4 5 5
 0 5 5 5 4 4 3 5 0 5 5 5 5 5 3 1 5 5 0 4 5 5 0 5 4 5 0 5 5 4 5 5 4 5 5 5 5
 5 5 5 4 5 5 5 5 5 5 0 5 5 4 3 3 5 3 5 5 3 5 0 5 0 5 0 5 5 5 5 5 5 3 5 5 3
 5 3 5 5 5 5 0 5 3 5 5 4 4 5 5 4 5 4 5 5 5 5 5 5 5 0 5 5 5 3 2 5 5 5 5 5 4
 5 4 4 5 4 5 3 5 5 3 5 5 5 1 5 5 5 4 5 5 5 5 4 4 5 4 5 5 5 5 3 4 4 5 4 2 5
 5 3 5 5 5 4 5 5 5 5 5 5 5 5 0 5 5 5 2 5 5 5 5 4 5 5 5 0 5 4 5 0 5 0 4 3 3
 5 1 3 3 3 2 3 5 5 4 4 4 5 4 2 0 5 5 5 5 5 5 5 5 5 5 4 0 4 5 5 5 5 4 5 4 3
 5 5 3 0 5 4 4 5 4 5 3 5 5 0 5 3 5 5 5 5 5 3 0 4 3 4 5 5 4 5 5 5 5 5 5 4 4
 4 5 5 4 3 5 0 5 3 5 5 5 

In [ ]:
print(y_test)

[5 5 5 5 5 4 5 5 5 5 5 4 5 5 5 5 5 5 0 3 5 0 5 5 4 5 5 5 5 5 5 3 3 5 4 5 5
 4 5 2 5 5 5 3 3 5 0 5 0 5 5 5 5 5 5 1 5 4 5 0 5 5 1 5 3 5 5 4 3 5 1 5 5 2
 4 4 5 5 4 5 5 5 0 5 5 3 5 5 5 3 5 5 3 5 5 5 5 1 5 5 5 0 1 5 4 0 3 5 3 5 5
 4 3 5 3 4 0 3 5 0 5 5 4 5 1 5]


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 1:] = sc.fit_transform(x_train[:, 1:])
x_test[:, 1:] = sc.transform(x_test[:, 1:])

In [ ]:
print(x_train)

[[ 39   0]
 [ 65   0]
 [375   1]
 ...
 [440   0]
 [579   0]
 [ 49   0]]


In [ ]:
print(x_test)

[[261   0]
 [214   0]
 [332   0]
 [459   0]
 [448   0]
 [187   0]
 [313   0]
 [131   0]
 [396   0]
 [ 91   0]
 [483   0]
 [ 35   0]
 [417   0]
 [488   0]
 [  2   0]
 [567   0]
 [422   0]
 [352   0]
 [379   0]
 [626   0]
 [ 78   0]
 [218   0]
 [385   0]
 [408   0]
 [ 75   0]
 [107   0]
 [ 24   0]
 [372   0]
 [415   0]
 [329   0]
 [ 88   0]
 [ 67   0]
 [513   0]
 [ 61   0]
 [419   0]
 [301   0]
 [363   0]
 [ 97   0]
 [197   0]
 [287   0]
 [620   0]
 [280   0]
 [333   0]
 [390   0]
 [523   0]
 [ 96   0]
 [285   0]
 [350   0]
 [148   0]
 [496   0]
 [540   0]
 [271   0]
 [617   0]
 [ 47   0]
 [345   0]
 [200   0]
 [444   0]
 [171   0]
 [355   0]
 [544   0]
 [ 36   0]
 [466   0]
 [193   6]
 [286   0]
 [275   0]
 [597   0]
 [299   0]
 [492   0]
 [  6   0]
 [456   0]
 [249   1]
 [421   0]
 [295   0]
 [615   0]
 [ 55   0]
 [166   0]
 [529   0]
 [195   0]
 [ 23   0]
 [391   0]
 [365   0]
 [ 43   0]
 [395   0]
 [501   0]
 [251   0]
 [185   0]
 [604   0]
 [451   0]
 [371   0]
 [536   0]
 [161   0]